
WINDOW_TITLE = 'Pixel Chess'
FPS = 30
SCALE_FACTOR = 3

WINDOW_WIDTH = 250 * SCALE_FACTOR
WINDOW_HEIGHT = 250 * SCALE_FACTOR
SQUARE_SIZE = 25 * SCALE_FACTOR

BOARD_SIZE = SQUARE_SIZE * 8

FEN_START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR'

